backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

media_library:
  name: It's a Date Assets
  config:
    cloud_name: itsadateapp
    api_key: 632918356145438

# field
# fields:
#   - { name: image, widget: image, media_library: { output_filename_only: false } }

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - {
          name: Hero Image,
          widget: image,
          media_library: { output_filename_only: false },
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Post Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          searchFields: ['name'],
          valueField: 'name',
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
  # - label: 'Settings'
  #   name: 'settings'
  #   files:
  #     - name: 'authors'
  #       label: 'Authors'
  #       file: 'src/pages/authors.yml'
  #       extension: 'yml'
  #       widget: 'list'
  #       fields:
  #         - label: 'Author'
  #           name: 'author'
  #           widget: 'list'
  #           fields:
  #             - { label: 'Name', name: 'name', widget: 'string' }
  #             - { label: 'About', name: 'about', widget: 'string' }
  #             - label: 'Profile Image'
  #               name: 'thumbnail'
  #               widget: 'image'
